# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedpost',
            name='user',
        ),
        migrations.AddField(
            model_name='blockedpost',
            name='blocked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockedpost',
            name='blocked_whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_whom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedpost',
            name='is_user_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blockedpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
