# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadWordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField(choices=[(1, 'admin'), (2, 'user')], default='1')),
                ('usercount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'badwords_list',
            },
        ),
    ]
